apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: pulsar
  name: pulsar
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pulsar
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: pulsar
    spec:
      containers:
        - args:
            - bin/pulsar
            - standalone
          env:
            - name: PULSAR_MEM
              value: -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g
          image: apachepulsar/pulsar:4.0.2
          name: pulsar
          ports:
            - containerPort: 6650
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
